### ISSUE TITLE
Connecting to a nebula managr hosted at a non root path

### ISSUE THREAD

**Issue by vineyyadav** [nebula-orchestrator/worker#145]
## Expected/Wanted Behavior
I had to host my manager at a non root path e.g. https://example.com/manager but the worker configuration does not allow for providing the path.

## Actual Behavior
Providing envvar `NEBULA_MANAGER_HOST="example.com/manager"` does not work as the manager URI is constructed inside the worker as: `protocol + "://" + host + ":" + str(port)`

## A possible suggestion
Add support for another env var NEBULA_MANAGER_URI and corresponding config var nebula_manager_uri using which user can provide the full URI (including protocol, host, port and any optional path) of manager e.g. `NEBULA_MANAGER_URI="https://example.com:8080/manager"`

If provided, URI should be used as it is, else constructed as being done currently.

If this suggestion sounds good, I can create a patch and raise PR.

**Comment by naorlivne** [comment]
Sounds good to me, and always nice getting a new contributor

**Comment by naorlivne** [comment]
Also this change will be needed to be done in https://github.com/nebula-orchestrator/nebula-python-sdk rather then just in the worker
