### ISSUE TITLE
Query about a container running standalone script !!

### ISSUE THREAD

**Issue by joshibhu** [nebula-orchestrator/worker#147]
## Expected/Wanted Behavior
A container which runs a script and simply exit should not be restarted by worker while fetching the cpnfiguration again from master.
 
## Actual Behavior
The actual behavior is when worker fetches the configuration again with master, it re-runs it and the script gets executed again. 

## Steps to Reproduce the Problem

  1. Run an application having standalone behavior
  2. Configure it in master against a device group already associated with a worker.
  3. Check if the worker keeps on re-run it.

**Comment by naorlivne** [comment]
This isn't a bug but rather more of an additional feature request.

Nebula was built for long running tasks and cron-jobs, if I'm understanding what your asking correctly this is to have the ability to run one-shot jobs as well, this isn't currently possible in nebula as it poses a few questions that are quite difficult to answer as the answer will depend on the end-user use case:

* What about devices that are joined the device group after the command is given? should the job run on them as well?
* Should the job run as truly one off or every device restart?
   * If truly one off how do we know on each device that the job already ran between runs? this will require stateful storage on each device and will mean the worker is no longer truly stateless
* Should jobs retry on failures or not?
* if we update a job does it need to rerun?

This is just off the top of my head so I'm sure that there will be dozens (if not more) other questions and use-cases that will need to be considered to have that one-time job option be viable and as I don't like the idea of putting half baked features in I prefer to have all the questions answered and a clear path ahead of what's needed before any work on new features will be started.

**Comment by joshibhu** [comment]
Thanks. Satisfied with the answer.
