### ISSUE TITLE
Prune image API not working

### ISSUE THREAD

**Issue by e01953** [nebula-orchestrator/worker#150]
**## Expected/Wanted Behavior**
All unused images should get prune

**## Actual Behavior**
Pruning not working

**## Steps to Reproduce the Problem**
  1. Create an app (e.g. 'nativeexecution') with hello-world as docker image and associate with device group(e.g.iotDevice)
  2. Update the docker image as "nginx" in app(nativeexecution) with configuration API.
  3. docker images in terminal -> 3 images are showing 1) Nebula worker 2) hello-world 3) nginx
  4. Used the prune API to remove the unused Images but all images are showing none of them was prune.

**Comment by naorlivne** [comment]
We seems to have hit https://github.com/docker/docker-py/issues/1939 with this bug, the fix stated in the link should work here as well so I'll add that in

**Comment by naorlivne** [comment]
pushed to latest, fix will be added to next versioned build (but you can of course test on latest meanwhile)
